"""create meetings table

Revision ID: 0244d411f4fa
Revises: 67956badf3c1
Create Date: 2026-06-28 14:58:28.385870

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0244d411f4fa"
down_revision: Union[str, Sequence[str], None] = "67956badf3c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meetings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("is_cancelled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_meetings_time_range")),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["users.id"], name=op.f("fk_meetings_creator_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["users.id"],
            name=op.f("fk_meetings_participant_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_meetings_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
    )
    op.create_index(
        op.f("ix_meetings_creator_id"), "meetings", ["creator_id"], unique=False
    )
    op.create_index(
        op.f("ix_meetings_participant_id"), "meetings", ["participant_id"], unique=False
    )
    op.create_index(op.f("ix_meetings_team_id"), "meetings", ["team_id"], unique=False)
    op.create_index(op.f("ix_meetings_title"), "meetings", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meetings_title"), table_name="meetings")
    op.drop_index(op.f("ix_meetings_team_id"), table_name="meetings")
    op.drop_index(op.f("ix_meetings_participant_id"), table_name="meetings")
    op.drop_index(op.f("ix_meetings_creator_id"), table_name="meetings")
    op.drop_table("meetings")
    # ### end Alembic commands ###
