"""create evaluations table

Revision ID: 67956badf3c1
Revises: dbaeb57310c7
Create Date: 2026-06-28 10:37:54.796456

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67956badf3c1"
down_revision: Union[str, Sequence[str], None] = "dbaeb57310c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("evaluator_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "score >= 1 AND score <= 5", name=op.f("ck_evaluations_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["evaluator_id"],
            ["users.id"],
            name=op.f("fk_evaluations_evaluator_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_evaluations_task_id_tasks")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_evaluations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluations")),
        sa.UniqueConstraint("task_id", name="uq_evaluations_task_id"),
    )
    op.create_index(
        op.f("ix_evaluations_evaluator_id"),
        "evaluations",
        ["evaluator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluations_task_id"), "evaluations", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluations_user_id"), "evaluations", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evaluations_user_id"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_task_id"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_evaluator_id"), table_name="evaluations")
    op.drop_table("evaluations")
    # ### end Alembic commands ###
