"""add team id to tasks

Revision ID: 6ff423e55f82
Revises: 531bb36c12aa
Create Date: 2026-06-25 14:10:20.509291

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ff423e55f82"
down_revision: Union[str, Sequence[str], None] = "531bb36c12aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("team_id", sa.Integer(), nullable=True))
    op.execute("""
    UPDATE tasks
    SET team_id = users.team_id
    FROM users
    WHERE tasks.creator_id = users.id
    """)
    op.alter_column("tasks", "team_id", nullable=False)
    op.create_index(op.f("ix_tasks_team_id"), "tasks", ["team_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_tasks_team_id_teams"), "tasks", "teams", ["team_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_tasks_team_id_teams"), "tasks", type_="foreignkey")
    op.drop_index(op.f("ix_tasks_team_id"), table_name="tasks")
    op.drop_column("tasks", "team_id")
    # ### end Alembic commands ###
